config/routes.rb
Rails.application.routes.draw do
  resources :caters
  resources :wedding_caters
  resources :wedding_venues
  resources :appointments
  resources :users

  get "/sessions/new", to: "sessions#new", as: "login" #login_path
  get "/login", to: "sessions#new"
  delete "/sessions", to: "sessions#destroy"
  post "/sessions", to: "sessions#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord

  belongs_to :user
  belongs_to :wedding_venue
end

app/models/cater.rb
class Cater < ApplicationRecord
  has_many :wedding_caters
  has_many :wedding_venues, through: :wedding_caters
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :email, uniqueness: true
  validates :phone_number, uniqueness: true
  
  has_many :appointments, :dependent => :destroy
  has_many :wedding_venues, through: :appointments
end

app/models/wedding_cater.rb
class WeddingCater < ApplicationRecord
  belongs_to :cater
  belongs_to :wedding_venue
end

app/models/wedding_venue.rb
class WeddingVenue < ApplicationRecord
  has_many :appointments, :dependent => :destroy
  has_many :users, through: :appointments
  has_many :wedding_caters
  has_many :caters, through: :wedding_caters

  validates :name, presence: true
  validates :location, presence: true
  validates :full_bar, presence: true
  validates :guest_accommodation, presence: true
  validates :wedding_style, presence: true
  validates :img_url, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def authorized
    redirect_to login_path unless logged_in
  end

  def current_user
    if session[:user_id]
      current_user = User.find(session[:user_id])
    end
  end

  def logged_in
    !!current_user
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :get_appointment, only: [:show, :edit, :update, :destroy] # do destroy
   before_action :authorized

  def index
    @appointments = Appointment.all
  end

  def show
  end

  def new
    @appointment = Appointment.new
    render :new
    @all_venues
  end

  def create
    venue = WeddingVenue.find(appointment_params[:wedding_venue_id])
    @appointment = Appointment.create!(user: current_user, wedding_venue: venue, date: appointment_params[:date])
    if @appointment.valid?
      redirect_to current_user
    else
      render :new
    end
  end

  def edit
  end

  def update
    @appointment.update(appointment_params)
    redirect_to @appointment
  end

  def destroy
    app = Appointment.find(params[:id])
    if current_user == app.user
    app.destroy
    redirect_to user_path(current_user)
    end
  end

  private

  def appointment_params
    params.require(:appointment).permit(:date, :user_id, :wedding_venue_id, :is_private)
  end

  def get_appointment
    @appointment = Appointment.find(params[:id])
  end
  def user_weddings
    @all_venues = WeddingVenue.all
  end
end

app/controllers/caters_controller.rb
class CatersController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  render :new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    end
  end

  def destroy
    session.delete :user_id
    redirect_to login_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_user, only: [:show, :edit, :update, :destroy] # do destroy
  before_action :authorized, except: [:new, :create]

  def index
    @users = User.all
  end

  def show
    if @user != current_user
      @appointments = @user.appointments.where(is_private: false)
    else
      @appointments = @user.appointments
    end
      render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
# byebug
    redirect_to @user
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    @user.update(user_params)
    if @user.valid?
    redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :phone_number, :email, :password, :password_confirmation)
  end

  def get_user
    @user = User.find(params[:id])
  end
end

app/controllers/wedding_caters_controller.rb
class WeddingCatersController < ApplicationController

  def new
    @wedding_cater = WeddingCater.new
    all_caters
  end

  def create

cater = Cater.find(wedding_cater_params[:cater_id])

venue = WeddingVenue.find(wedding_cater_params[:wedding_venue_id])
    @wedding_cater = WeddingCater.create!(cater: cater, wedding_venue: venue )
    redirect_to @wedding_venue

# wedding_cater needs wedding_venue_id and cater_id in params
# wedding_cater_params wont work because you need to pass in the instances not the id's. it can't read what :wedding_venue_id and cater_id is.

  end

  private

  def wedding_cater_params
    params.require(:wedding_cater).permit(:wedding_venue_id, :cater_id)
  end

  def all_caters
    @all = Cater.all
  end
end

app/controllers/wedding_venues_controller.rb
class WeddingVenuesController < ApplicationController

  before_action :get_wedding_venue, only: [:show, :edit, :update, :destroy] # do destroy

  def index
    @wedding_venues = WeddingVenue.all
  end

  def show
  end

  def new
    @wedding_venue = WeddingVenue.new
    all_caters
  end

  def create
    @wedding_venue = WeddingVenue.create(wedding_venue_params)
    if @wedding_venue.valid?
    redirect_to @wedding_venue
    else
      render :new
    end
  end

  def edit
  end

  def update
    @wedding_venue.update(wedding_venue_params)
    if @wedding_venue.valid?
    redirect_to @wedding_venue
    else
      render :edit
    end
  end

  def destroy
    @wedding_venue.destroy
    redirect_to wedding_venues_path
  end

  private

  def all_caters
    @all = Cater.all
  end

  def wedding_venue_params
    params.require(:wedding_venue).permit(:name, :location, :cost, :full_bar, :guest_accommodation, :wedding_style, :img_url, :cater_ids)
  end

  def get_wedding_venue
    @wedding_venue = WeddingVenue.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/caters_helper.rb
module CatersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wedding_caters_helper.rb
module WeddingCatersHelper
end

app/helpers/wedding_venues_helper.rb
module WeddingVenuesHelper
end

app/views/appointments/edit.html.erb
<h1>Edit Appointment</h1>

<%= form_for @appointment do |f| %>
Date:
<%= f.date_field :date %><br><br>


Wedding Venue: <%= f.collection_select(:wedding_venue_id, WeddingVenue.all, :id, :name) %>
<%= f.submit %>
<% end %>

app/views/appointments/index.html.erb
<h1>All Appointments</h1>

<% @appointments.each do |appointment| %>
<%= appointment.date %>
<% end %>

<%= link_to "New Appointments", new_appointment_path %>

app/views/appointments/new.html.erb
<h1>Add a new Appointment</h1>

<%= form_for @appointment do |f| %>
Date:
<%= f.date_field :date %><br><br>


Wedding Venue: <%= f.collection_select(:wedding_venue_id, WeddingVenue.all, :id, :name) %>
<%= f.submit %>
<% end %>

app/views/caters/index.html.erb
<h1>All Caters!</h1>

<% @caters.each do |cater| %>
<%= cater.name %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeddingPlannerApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<% if @user.errors %>
<% @user.errors.full_messages.each do |message| %>
<%= message %>
<% end %>
<% end %>

<ol>
<%= form_for @user do |f| %>
<li><%= f.label :name %>
<%= f.text_field :name %>
<li><%= f.label :email %>
<%= f.email_field :email %>
<li><%= f.label :password %>
<%= f.password_field :password %>
<li><%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<li><%= f.label :phone_number %>
<%= f.text_field :phone_number %><br>
<%= f.submit %>
<% end %>
</ol>

app/views/users/index.html.erb
<h1>All Users!</h1>

<ul>
<% @users.each do |user| %>
<li><%= link_to user.name, user %></li>
<% end %>
</ul>
<br><br>
<%= link_to "Create New User", new_user_path %>

app/views/users/new.html.erb
<h1>Create New User</h1>

<% if @user.errors %>
<% @user.errors.full_messages.each do |message| %>
<%= message %>
<% end %>
<% end %>

<ol>
<%= form_for @user do |f| %>
<li><%= f.label :name %><br>
<%= f.text_field :name %></li>
<li><%= f.label :email %><br>
<%= f.email_field :email %></li>
<li><%= f.label :password %><br>
<%= f.password_field :password %></li>
<li><%= f.label :password_confirmation %><br>
<%= f.password_field :password_confirmation %></li>
<li><%= f.label :phone_number %><br>
<%= f.text_field :phone_number %></li>
<%= f.submit %>
<% end %>
</ol>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<h4>E-mail: <%= @user.email %></h4>
<h4>Phone Number: <%= @user.phone_number %></h4>
<br><br><br>



<ol>  <h4>All Appointments</h4>
<% @user.appointments.each do |appointment| %>
<li> Wedding Venue:<%= link_to appointment.wedding_venue.name, appointment.wedding_venue %><br>
Date: <%= appointment.date %></li><br>

<% end %>
</ol>
<br><br>
<%= link_to "Back to Users", users_path %><br>
<%= link_to "Add Appointment", new_appointment_path %><br>
<%= link_to "Edit #{@user.name}", edit_user_path %><br>
<%= link_to "Delete #{@user.name}", @user, method: :delete %>

app/views/wedding_venues/edit.html.erb
<h1>Edit <%= @wedding_venue.name %></h1>

<% if @wedding_venue.errors %>
<% @wedding_venue.errors.full_messages.each do |message| %>
<%= message %>
<% end %>
<% end %>

<ol>
<%= form_for @wedding_venue do |f| %>
<li><%= f.label :name %>
<%= f.text_field :name %></li>
<li><%= f.label :location %>
<%= f.text_field :location %></li>
<li><%= f.label :cost %>
<%= f.text_field :cost %></li>
<li><%= f.label :full_bar %>
<%= f.text_field :full_bar %></li>
<li><%= f.label :guest_accommodation %>
<%= f.text_field :guest_accommodation %></li>
<li><%= f.label :wedding_style %>
<%= f.text_field :wedding_style %></li>
<li><%= f.label :img_url %>
<%= f.text_field :img_url %></li>
<li>Cater: <%= f.collection_select(:cater_ids, Cater.all, :id, :name) %></li>
<%= f.submit %>
<% end %>
</ol>

app/views/wedding_venues/index.html.erb
<h1>All Wedding Venues!</h1>
<%= link_to "Create new Venue", new_wedding_venue_path %>
<br><br><br><br>
<ul>
<br><% @wedding_venues.each do |wedding_venue| %>
<img src="<%= wedding_venue.img_url %>" style="width:400px;height:300px;">
<li><%= link_to wedding_venue.name, wedding_venue %></li>
<li>Location: <%= wedding_venue.location%></li><br><br><br>
<% end %>

</ul><br><br>

app/views/wedding_venues/new.html.erb
<h1>Create a new Wedding Venue</h1>

<% if @wedding_venue.errors %>
<% @wedding_venue.errors.full_messages.each do |message| %>
<%= message %>
<% end %>

<ol>
<%= form_for @wedding_venue do |f| %>
<li><%= f.label :name %>
<%= f.text_field :name %></li>
<li><%= f.label :location %>
<%= f.text_field :location %></li>
<li><%= f.label :cost %>
<%= f.text_field :cost %></li>
<li><%= f.label :full_bar %>
<%= f.text_field :full_bar %></li>
<li><%= f.label :guest_accommodation %>
<%= f.text_field :guest_accommodation %></li>
<li><%= f.label :wedding_style %>
<%= f.text_field :wedding_style %></li>
<li><%= f.label :img_url %>
<%= f.url_field :img_url %></li>
<li>Cater: <%= f.collection_select(:cater_ids, Cater.all, :id, :name) %></li>
<%= f.submit %>
<% end %>
</ol>

app/views/wedding_venues/show.html.erb
<h1><%= @wedding_venue.name %></h1>
<img src="<%= @wedding_venue.img_url %>" style="width:400px;height:300px;">
<br><br><br>

<li>Location: <%= @wedding_venue.location%></li>
<li>Wedding Style: <%= @wedding_venue.wedding_style%></li>
<li>Cost: <%= @wedding_venue.cost%></li>
<li>Guest Accomodation: <%= @wedding_venue.guest_accommodation%></li>
<li>Included Full Bar: <%= @wedding_venue.full_bar%></li>
<li>Cater Associated:
  <% @wedding_venue.caters.each do |cater| %>

  <%= cater.name %>
  <% end %>
</li><br><br>
<br><br>

<ol>
Upcoming Appointments:<br>
<li><% @wedding_venue.appointments.each do |appointment| %>
Client: <%= appointment.user.name %><br>
Date: <%= appointment.date %></li>

<% end %></ol><br><br>

<%= link_to "Back to Venues", wedding_venues_path %><br>
<%= link_to "Delete #{@wedding_venue.name}", @wedding_venue, method: :delete %><br>
<%= link_to "Edit #{@wedding_venue.name}", edit_wedding_venue_path %><br><br><br>
<%= link_to "Delete Appointment", @appointment, method: :delete %>